Создал файл function в котором проверяются строки
htmlacademy-javascript/1802891-kekstagram-30 pull request #2
Opened 2023-10-10 10:38 UTC by Shepard-m

2023-10-10 10:52 UTC, ademaro commented on js/functions.js
> +  string.length <= length ? true : false;
А где `return`?

2023-10-10 10:52 UTC, ademaro commented on js/functions.js
> +  string.length <= length ? true : false;
Ну и можно упростить: `return string.length <= length;`

2023-10-10 10:53 UTC, ademaro commented on js/functions.js
> +  return (normalizeString === comparisonString) ? true : false;
Тут так же убираем тернарный оператор, тк оператор сравнения уже нам возвращает boolean

2023-10-10 10:54 UTC, ademaro commented on js/newFile.js
> +console.log(checkingPalindrome("TT"));
почему в новом файле?)

2023-10-10 10:54 UTC, ademaro requested changes
Жду поправок, завтра обсудим делальнее

2023-10-10 11:16 UTC, Shepard-m commented on js/functions.js
> +  string.length <= length ? true : false;
Так, вроде, стрелочная функция может работать без return

2023-10-10 14:24 UTC, ademaro commented on js/functions.js
> +
```js
/**
 * Поиск чисел в строке
 * @param {string|int} string — исходная строка или целое число
 * @return {int} — найденные цифры из исходной строки
 */
```

2023-10-10 14:31 UTC, ademaro requested changes
Жду правки тогда

2023-10-11 10:26 UTC, Shepard-m commented on js/functions.js
> +const cheakLengthString = (string, length) => string.length <= length;
```js
/**
 * Считает длину строки
 * @param {string|int} — исходная строка или целое число
 * @return {boolean} — правду или ложь 
 * /

2023-10-11 10:32 UTC, Shepard-m commented on js/functions.js
> +const isPalindrome = (rawString) => {
```js
/**
 * проверяет строку на палиндром
 * @param {string} — исходная строка
 * @return {boolean} — правду или ложь 
 */

2023-10-11 13:18 UTC, ademaro approved these changes

2023-10-11 13:18 UTC, merged